name: CmakeCI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install -y clang git cmake libopenblas-dev
    - name: cmake_blas_true_simd_false
      run: |
        mkdir tmp && cd tmp
        CXX=clang++ CC=clang cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SIMD=OFF -DUSE_BLAS=ON ..
        cmake --build . --parallel
        ctest
        cd .. && rm -rf tmp
    - name: cmake_blas_true_simd_true
      run: |
        mkdir tmp && cd tmp
        CXX=clang++ CC=clang cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SIMD=ON -DUSE_BLAS=ON ..
        cmake --build . --parallel
        ctest
        cd .. && rm -rf tmp
